name: Publish

on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: |
          msbuild run-hidden.vcxproj -t:rebuild -verbosity:diag /p:Configuration=Release /p:Platform=x64
          msbuild run-hidden.vcxproj -t:rebuild -verbosity:diag /p:Configuration=Release /p:Platform=Win32

      - name: Publish archive
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release/Win32/run-hidden.exe
            Release/x64/run-hidden64.exe
